# Generated by Django 5.1.1 on 2024-12-03 08:32

import django_jalali.db.models
import jdatetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_token_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now),
        ),
    ]
